export const defaultLanguages = {
  bash: 'Bash',
  c: 'C',
  cpp: 'C++',
  css: 'CSS',
  go: 'Go',
  html: 'HTML',
  java: 'Java',
  js: 'JavaScript',
  kotlin: 'Kotlin',
  mathml: 'MathML',
  perl: 'Perl',
  ruby: 'Ruby',
  scala: 'Scala',
  sql: 'SQL',
  svg: 'SVG',
  swift: 'Swift',
  python: 'Python',
};
